### PR TITLE
Check entity support

### LINKED ISSUE #50: Remove unsupported entities from configurator menu
Entities not supported (by OS) should not be available in configurator menu.

This will be done after the addition of new OS get method (#30)

### PR DESCRIPTION
**Pull request by infeeeee**
Check if entity supported in configuration menu and before initialization. 

Entities should override the `CheckSystemSupport` class method, and raise an exception if the system is not supported, that's all. All related code from `Initialize` moved to this new classmethod in existing entities.

Resolves #50 

Based on #86 so it should be pulled before, and you can see that changes here as well, but if you don't want to pull that yet, I think I can rebase to `main`. 

If you want to see changes related to only this, see this comparison: https://github.com/infeeeee/IoTuring/compare/OpenInEditor...infeeeee:IoTuring:CheckEntitySupport

TODO, Remaining entities to update:
- [x] Power
- [x] Temperature

### CODE REVIEW

**Comment by richibrics** [comment]
Really nice, could you please rebase with the main new commits please ?

**Review by richibrics — APPROVED** [review]
Really like it

**Comment by infeeeee** [comment]
@richibrics Can you take a look at the new changes in the configurator menu? Now it handles small terminals much better. It also lists unsupported entities, and the reason why they are unsupported.

**Comment by richibrics** [comment]
Hi @infeeeee, it works really great. Nice job 👍

**Review by richibrics — APPROVED** [review]

**Pull request merged**
