### PR TITLE
Ydotool Entity

### PR DESCRIPTION
**Pull request by lockenkop**
https://github.com/ReimuNotMoe/ydotool

Ydotool is a universal input automation tool. 

I'll have to do some more testing in different wayland and x11 environments. Most features are working already on my hyprland DE laptop.

### CODE REVIEW

**Comment by richibrics** [comment]
for future needs: on linux it may need the following commands (as root) in order to fix the "failed to open uinput device" error.

```
usermod -aG input <USER_THAT_STARTS_IOTURING>
echo 'KERNEL=="uinput", GROUP="input", MODE="0660", OPTIONS+="static_node=uinput" ' | sudo tee /etc/udev/rules.d/80-uinput.rules > /dev/null
udevadm control --reload-rules && udevadm trigger
```

**Comment by lockenkop** [comment]
This should be feature complete now.
Ydotool supports reading files with a list of instructions in them. That's the only feature i didn't include, since i don't see much value in it in context of IoTuring.

**Comment by lockenkop** [comment]
I get your point. It doesn't add allot of value. I imagined this Entity to be interesting for the tech knowledge intermediate. 
Someone who might get overwhelmed by all the options and advanced syntax they have with those gui scripting automation tools.

**Comment by infeeeee** [comment]
Maybe adding some examples in Terminal commands instead? Or something like that?

A user should look up keyboard and other codes, so even this requires some documentation reading.  Writing the commands is not a big step from there.

I don't recommend pulling this as a separate entity, but @richibrics is the boss.

**Comment by lockenkop** [comment]
I'm fine with this PR being rejected with the infeeee's reasoning. It was a good practice and interesting topic for me nonetheless.

**Pull request closed without merging**
