### PR TITLE
pyproject.toml and setuptools

### PR DESCRIPTION
**Pull request by infeeeee**
Afaik using `requirements.txt` for setting up dependencies is discouraged nowadays, and the current recommended method is via `pyproject.toml`.

Also a lot of python tools are using this file to store there parameters there. 

I was just playing with [setuptools](https://setuptools.pypa.io/en/latest/index.html) as well. It can alias the script really nicely. Take a look my changes on readme. I also had to separate main.py to` __main__.py` and `__init__.py` as that's how they require to set up your project.

My endgoal with these changes to create an aur package from this project, and they require to use some kind of build and package system, so you can easily install your package system wide. It will be also useful if you want to create installer, or if you want to distribute this via other methods, e.g. pip. 

Also if this is set up correctly, the whole project with all dependencies could be installed via pip, so  the full install and configuation could be this easy:

```shell
pip install git+https://github.com/richibrics/IoTuring[linux]
IoTuring -c
```

Currently this is not working correctly on my fork yet, but I will figure it out.

Do you  have another favorite  python build tool? Is it ok if I play with things like this on your project? What do you think of these changes?

### CODE REVIEW

**Comment by richibrics** [comment]
Hi, sure it looks great.
This afternoon I'll take a look at the changes we need.

Thank you !

**Comment by infeeeee** [comment]
I figured it out finally, I had to change imports to use absolute paths.

Now this works, I pulled the changes to my main branch as well, you can try this:

```
git clone https://github.com/infeeeee/IoTuring
cd IoTuring
pip install .[linux]
IoTuring -c
```

Only reading the App.description is not working, but maybe we could read that data from pyproject.toml?

For working on the code simply install it in [editable/development mode](https://setuptools.pypa.io/en/latest/userguide/development_mode.html):
```
pip install -e .[linux]
```

**Comment by infeeeee** [comment]
I fixed everything, take a look at the readme. On my main branch everything works, so you just have to replace your name with mine on the github links.

Tested on win, arch, debian, ubuntu.

**Comment by richibrics** [comment]
Wow... very nice that I can install it using pip with all dependencies downloaded with the script !
Great work !

There's only a problem I think: I tried the HomeAssistantWH and it can't find the YAML file 'Warehouse/Deployments/HomeAssistantWarehouse/entities.yaml': pip is not copying that file in the IoTuring folder.
I'm looking for reasons now.

**Comment by richibrics** [comment]
Probably should we add an include parameter in the toml file for the "yaml" extension ?

**Comment by infeeeee** [comment]
> Probably should we add an include parameter in the toml file for the "yaml" extension ?

Yes that should be the problem: https://setuptools.pypa.io/en/latest/userguide/datafiles.html

I can take a look later today. That's the only non `.py` file, right?

**Comment by richibrics** [comment]
Yes it's the only one

**Comment by infeeeee** [comment]
Done, it's now included, tested it. That last line is a list, other non py files should be added there in the future as well.

**Comment by infeeeee** [comment]
2 other things: 

- Version number: Now it will become important, as pip will update the package based on this number. 1.0.0 usually means the software is mature, and mostly finished. I think using 0.0.1 as the first version number could be better. Or consider date based versioning instead (like homeassistant), when the app is never finished. I think using 1.0.0 at the current state can be confusing.
- The make file not working with this new install method should we remove it or maybe just update it? It's also confusing that it's there but not working.

**Comment by richibrics** [comment]
Very nice.
The other things:
- I like a YYYY.0M.0D.Micro format like [here](https://github.com/relizaio/versioning). My idea was to find/make an Action to release this and automatically set the extension but I'm looking for a solution currently.
- We could remove the Makefile as I wasn't really using it.

**Comment by infeeeee** [comment]
Github Actions would useful for this, I never used it, but doesn't seems very complicated.

Some linting could be automated as well.

For small personal snippets checkout vscode tasks: https://code.visualstudio.com/Docs/editor/tasks Similar usecase to the makefile.

I think everything is ready now.

**Comment by richibrics** [comment]
Perfect.
I have a question: wouldn't it be better with a micro number after the day to be able to release two versions in a day ?

Like 2022.02.03.1, 2022.02.03.2

What do you think about this ?

**Comment by richibrics** [comment]
Last question (that I could do by myself): since we moved all files in the IoTuring folder, what do you think if we use this directory structure ?

src/IoTuring/...
test/IoTuring/...
dist/ (automatically built by Python -m build)

**Comment by infeeeee** [comment]
> Perfect. I have a question: wouldn't it be better with a micro number after the day to be able to release two versions in a day ?
> 
> Like 2022.02.03.1, 2022.02.03.2
> 
> What do you think about this ?

I would use the micro number instead of the day, not next to it. I think it won't be that common that multiple releases happen in one day, and setting the date before a pull wouldn't be possible. E.g. I used now 2022.11.29, but if you pull it tomorrow, than the date won't be correct, so it would have to be changed again. Nearly midnight here as well, in Asia it's already tomorrow.

I would use 2022.11.1 than for the next release in November 2022.11.2, etc. It's not that strict, and it works better as a day is not easily defined around the globe. Extreme example: ([source](https://en.wikipedia.org/wiki/International_Date_Line#Facts_dependent_on_the_IDL))

> For example, at 10:15 UTC Thursday, it is 23:15 Wednesday in American Samoa ([UTC−11:00](https://en.wikipedia.org/wiki/UTC%E2%88%9211:00)), Thursday in most of the world, and 00:15 Friday in [Kiritimati](https://en.wikipedia.org/wiki/Kiritimati) ([UTC+14:00](https://en.wikipedia.org/wiki/UTC%2B14:00)).

---

> Last question (that I could do by myself): since we moved all files in the IoTuring folder, what do you think if we use this directory structure ?
> 
> src/IoTuring/... test/IoTuring/... dist/ (automatically built by Python -m build)

I think the current layout is ok, I was thinking about this as well. Setuptools calls this a [Flat Layout](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#flat-layout), and automatic discovery works. 

Examples: 
- [psutil](https://github.com/giampaolo/psutil) uses the same layout, they place tests inside the the main folder
- [pykeepass](https://github.com/libkeepass/pykeepass) uses this as well, they place the tests in the root directly.

What else do you think will be placed in src? I think that layout is better for projects which has multiple separate modules, [monorepos](https://en.wikipedia.org/wiki/Monorepo)

Like this, here they have 28 (!) tools in one repo: https://github.com/IfcOpenShell/IfcOpenShell

**Comment by richibrics** [comment]
Thank you for your constant support.
You convinced me on both questions:
- it's okay for me to use the date format with the micro number without the day, since there could be timezone conflicts.
- I will add the test folder in the root folder (like pykeepass), and not in the IoTuring folder (like psutil) to keep source and test code separated.

Thank you !

**Review by richibrics — APPROVED** [review]
Everything's okay

**Pull request merged**
