### PR TITLE
Menu with arrow navigation for config

### PR DESCRIPTION
**Pull request by infeeeee**
Full arrow based navigation for configuration, with this library: https://github.com/IngoMeyer441/simple-term-menu

### CODE REVIEW

**Comment by infeeeee** [comment]
Oh no! This library doesn't work on windows... There is a pull request for windows support, I tried that branch, but it's somewhat working... So wait with this until it's pulled there (Or maybe I will put back the old system as a fallback?)

https://github.com/IngoMeyer441/simple-term-menu/pull/34

**Comment by richibrics** [comment]
This is stunning, I tried this some weeks ago. 
I don't think they're currently working on a Windows version so I think we could adopt this for Linux/macOS and leave Windows as it is now (for the moment)

**Comment by infeeeee** [comment]
For future reference, possible alternatives:

- [dumb_menu](https://github.com/cornradio/dumb_menu)
- [python-inquirer](https://github.com/magmax/python-inquirer)

**Comment by richibrics** [comment]
Nice, [python-inquirer](https://github.com/magmax/python-inquirer) seems really well done. 
I think this is a good point where to start when I will find time in the future to come back strongly on this project.

**Comment by infeeeee** [comment]
Rewrite: #83

**Pull request closed without merging**
