### PR TITLE
Build Docker image

### PR DESCRIPTION
**Pull request by infeeeee**
Tested, most of the entities work in docker, psutil can read a lot of things. Obviously monitor related things fail, but it's expected, I had to add another check for `ActiveWindow`.

@richibrics Can you create a new release, to check if everything is working as expected? Docker image should build automatically, I tested it on my fork, but not from a release. It should automatically read the version if started from a tag.

### CODE REVIEW

**Comment by richibrics** [comment]
Hi @infeeeee,
I thought about using Docker many times but I always ended thinking that a lot of computer information wouldn't be available inside a container.
For example, do the CPU and RAM entities work as expected ?

**Comment by infeeeee** [comment]
Works:
- CPU
- RAM
- Disk
- Temperature
- Uptime
- Terminal

Wrong value, as expected:
- Username - always root
- Desktop Environment
- Time, if timezone is not setup correctly in the container, see TZ envvar in compose

Of course this is on a linux host. On windows, docker usually runs in a linux VM aka WSL2. There are windows based containers, I never used them. I have no idea how docker works on macos.

Docker uses the same kernel as the host, and afaik these psutil calls are just kernel calls so they work in docker as well. Docker is not a virtual machine, just a container. File system, network and memory is separated, but the kernel isn't.

I wasn't the first who tried this, I found this, so I thought it should work: https://github.com/tflash/docker-psutil

Currently this is only x64 and linux, but if the build action works, I would figure out how to build for arm and native windows.

**Comment by infeeeee** [comment]
Oh and you can try it, I accidentally created an image while tried to set up the action:

https://github.com/infeeeee/IoTuring/pkgs/container/ioturing

**Comment by richibrics** [comment]
Well, that is so great !

**Comment by richibrics** [comment]
Added DockerHub repository

**Review by richibrics — APPROVED** [review]

**Pull request merged**
