### PR TITLE
Open configuration file in editor

### PR DESCRIPTION
**Pull request by infeeeee**
- Use `argparse` library for argument parsing: Easier to add new options, version info and help:

```
> IoTuring --help
usage: IoTuring [-h] [-v] [-c] [-o]

Simple and powerful cross-platform script to control your pc and share statistics using communication protocols like MQTT and home control hubs like HomeAssistant.

options:
  -h, --help          show this help message and exit
  -v, --version       show program's version number and exit
  -c, --configurator  enter configuration mode
  -o, --open-config   open config file

Start without argument for normal use
> IoTuring --version
IoTuring 2023.11.1
```

- New start argument: `-o, --open-config`: Open config file
Maybe help with #85
On windows it opens in the editor associated with json files. On Mac and Linux it tries the following editors in this order:
  - What set in the `$EDITOR` envvar
  - `nano`
  - `vim`

@richibrics Please check if this is working on Mac. I know `nano` is installed on recent MacOS versions by default

Other changes:

- Update minimum Python version to 3.8, as 3.7 is EOL: https://devguide.python.org/versions/
- `importlib.metadata` is available as a std lib in 3.8, so `importlib_metadata` backport is not needed anymore
- Use Dockerhub links in readme and compose, instead of ghcr. It's shorter, and looks better
- `ConfiguratorIO`: Menu for old configuration moved to `Configurator`, modernize, use Pathlib.
- `Configurator`: small changes, when to clear the screen
- Log related: 
  - Catch exception for wrong loglevel from envvar. 
  - Store envvar loglevel (Previously each log line asked for the envvar. I guess this should be some performance improvement)
- `OperatingSystemDetection`: `OsD.GetEnv()` now works on every platform, not just on Linux :)

Tested on Linux and Windows

### CODE REVIEW

**Comment by richibrics** [comment]
on macOS it doesn't use anymore the Library folder. I'll take a look soon

**Comment by richibrics** [comment]
Fixed the macOS problem that was related with OsDetection, and everything is great and works !
LGTM 🚀

**Review by richibrics — APPROVED** [review]

**Comment by richibrics** [comment]
@infeeeee I was thinking, should we say which are the available env vars somewhere ? For example in the help messages ?

**Comment by infeeeee** [comment]
> @infeeeee I was thinking, should we say which are the available env vars somewhere ? For example in the help messages ?

Maybe mentioning them more prominently in the readme would be enough? They are basically workarounds.

Recently read about pipx, and nowadays this is the recommended way of installing system wide python apps. E.g. recent ubuntu and debain don't let you install with pip outside a venv: https://github.com/pypa/pipx

**Comment by richibrics** [comment]
Agree with the envvars, being put in a "documentations" is enough.
About pipx: doesn't it isolate IoTuring in sense of sensors too right ? Because we work on some kernel parameters too

**Comment by infeeeee** [comment]
pipx is exactly the same as running it in a venv. It only isolates dependency and python versions, you can have different versions of psutils installed for different programs, they can reach everything the same way. No virtualization going on. Tried that in a VM, that's why I know systemwide pip is not recommended anymore.

Actually I always run and develop IoTuring in a venv, I think that's the easiest way to save yourself from python hell: https://xkcd.com/1987/

**Comment by richibrics** [comment]
Yeah fine then, we can work on it !

**Pull request merged**
